using System;
using System.IO;
using System.Linq;
using Cinemachine;
using TMPro;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.SceneManagement;
using UnityEngine.Timeline;
using UnityEngine.UI;

// One-shot Intro migration. All object IDs, track IDs and bindings are authored by Unity.
public static class IntroCutsceneSetupEditor
{
    public const string IntroPath = "Assets/_Game/Scenes/Intro.unity";
    public const string Folder = "Assets/_Game/Scenes/IntroSkeleton";
    public const string BarPath = Folder + "/Intro_BarSequence.playable";
    public const string DoorPath = "Assets/_Game/Scenes/Intro_DoorOpen.playable";

    public static void SetupBatch()
    {
        EditorSceneManager.OpenScene(IntroPath);
        SetupOpenScene();
        EditorSceneManager.SaveScene(SceneManager.GetActiveScene());
    }

    [MenuItem("Tools/Intro/Configure Final Intro")]
    public static void SetupOpenScene()
    {
        Scene scene = SceneManager.GetActiveScene();
        Require(!EditorApplication.isPlayingOrWillChangePlaymode && scene.path == IntroPath, "Open Intro in Edit Mode.");
        if (AssetDatabase.LoadAssetAtPath<TimelineAsset>(BarPath) != null)
        {
            ValidateOpenScene();
            Debug.Log("Final Intro already configured. Existing tuning was preserved.");
            return;
        }

        Transform model = All<Transform>(scene).Single(t => t.name == "PF_Dealer" &&
            PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(t.gameObject) ==
            "Assets/_Game/Art/Characters/Dealer/Models/PF_Dealer.prefab");
        Vector3 modelPosition = model.position;
        Quaternion modelRotation = model.rotation;
        PlayerMove player = All<PlayerMove>(scene).Single();
        CinemachineVirtualCamera playerView = player.GetComponentInChildren<CinemachineVirtualCamera>();
        Camera main = All<Camera>(scene).Single(c => c.CompareTag("MainCamera"));
        CinemachineBrain brain = main.GetComponent<CinemachineBrain>();
        IntroFlowController flow = All<IntroFlowController>(scene).Single();
        DialogueController dialogue = All<DialogueController>(scene).Single();
        IntroDoorTrigger door = All<IntroDoorTrigger>(scene).Single();
        PlayableDirector doorDirector = (PlayableDirector)new SerializedObject(door)
            .FindProperty("doorRevealDirector").objectReferenceValue;
        Require(playerView != null && brain != null && doorDirector != null, "Existing camera/door bindings are required.");
        Require(EditorBuildSettings.scenes.Any(s => s.enabled &&
            Path.GetFileNameWithoutExtension(s.path) == IntroFlowController.GameplaySceneName), "Gameplay is not enabled in Build Settings.");

        // Reuse the actual transition canvas but detach it from the obsolete skeleton before cleanup.
        GameObject fadeObject = Find(scene, "Gameplay Transition Fade").gameObject;
        fadeObject.transform.SetParent(null, true);
        Animator oldFadeAnimator = fadeObject.GetComponent<Animator>();
        if (oldFadeAnimator != null) UnityEngine.Object.DestroyImmediate(oldFadeAnimator);
        fadeObject.transform.localScale = Vector3.one;
        fadeObject.GetComponent<Canvas>().sortingOrder = 32760;
        fadeObject.GetComponent<CanvasGroup>().alpha = 0f;
        fadeObject.AddComponent<GraphicRaycaster>();
        Image black = fadeObject.GetComponentInChildren<Image>(true);
        black.raycastTarget = true;
        var fade = fadeObject.AddComponent<IntroFadeController>();
        Set(fade, "overlay", fadeObject.GetComponent<CanvasGroup>());

        foreach (string name in new[] { "Intro Skeleton", "Dealer_Model", "Cutscene A Camera", "Cutscene B Camera",
            "Intro Cutscene", "Cube", "Cube Start Point", "Cube End Point", "Interaction Button" })
        {
            Transform old = All<Transform>(scene).FirstOrDefault(t => t.name == name);
            if (old != null && old != model && !model.IsChildOf(old))
                UnityEngine.Object.DestroyImmediate(old.gameObject);
        }
        // Obsolete assets generated by the previous Intro implementation only.
        AssetDatabase.DeleteAsset(Folder + "/Intro_BarReveal.playable");
        AssetDatabase.DeleteAsset(Folder + "/Intro_TableSequence.playable");
        AssetDatabase.DeleteAsset(Folder + "/Intro_DealerIdle.controller");

        var root = new GameObject("Intro Sequence").transform;
        var target = new GameObject("Dealer Look Target").transform;
        target.SetParent(model, false);
        Renderer face = model.GetComponentsInChildren<Renderer>().Single(r => r.name == "Face");
        target.position = face.bounds.center + Vector3.up * 0.08f;
        Animator animator = model.gameObject.AddComponent<Animator>();
        animator.applyRootMotion = false;
        // This is a static mesh prefab: assigning another dealer's avatar cannot skin these meshes.
        var controller = AnimatorController.CreateAnimatorControllerAtPath(Folder + "/Intro_DealerPresentation.controller");
        AnimatorState idle = controller.layers[0].stateMachine.AddState("Standing Idle - Rig and Clip Required");
        controller.layers[0].stateMachine.defaultState = idle;
        controller.layers[0].stateMachine.AddState("Talk - Optional Rig and Clip");
        animator.runtimeAnimatorController = controller;

        main.transform.SetParent(null, true);
        brain.m_DefaultBlend = new CinemachineBlendDefinition(CinemachineBlendDefinition.Style.EaseInOut, 0.35f);
        playerView.Priority = 10;
        playerView.Follow = null;
        playerView.LookAt = null;
        // PlayerMove already supplies full rotation, so the player view uses no procedural body/aim.
        foreach (var component in playerView.GetComponentPipeline())
            UnityEngine.Object.DestroyImmediate(component);
        playerView.PreviousStateIsValid = false;

        var directorObject = new GameObject("Bar Sequence");
        directorObject.transform.SetParent(root, false);
        var director = directorObject.AddComponent<PlayableDirector>();
        director.playOnAwake = false;
        director.extrapolationMode = DirectorWrapMode.Hold;
        var path = new GameObject("Bar Camera Path").transform;
        path.SetParent(root, false);
        var pathAnimator = path.gameObject.AddComponent<Animator>();
        var cameraObject = new GameObject("BarSequence Camera");
        cameraObject.transform.SetParent(root, false);
        var virtualCamera = cameraObject.AddComponent<CinemachineVirtualCamera>();
        virtualCamera.Priority = 0;
        virtualCamera.m_Lens = playerView.m_Lens;
        var rig = directorObject.AddComponent<IntroBarSequenceCamera>();
        Set(rig, "director", director);
        Set(rig, "authoredPath", path);
        Set(rig, "virtualCamera", virtualCamera);

        BoxCollider doorBox = door.GetComponent<BoxCollider>();
        Vector3 entry = doorBox.bounds.center + Vector3.right * (doorBox.bounds.extents.x + 0.75f);
        entry.y = playerView.transform.position.y;
        Vector3 end = model.position + model.forward * 2.6f;
        end.y = entry.y;
        Vector3 middle = new Vector3(entry.x + 2.2f, entry.y, end.z);
        var arrival = new GameObject("Dealer Interaction View - Reference").transform;
        arrival.SetParent(root, false);
        arrival.SetPositionAndRotation(end, Quaternion.LookRotation(target.position - end));
        path.SetPositionAndRotation(entry, Quaternion.Euler(0f, 90f, 0f));
        virtualCamera.transform.SetPositionAndRotation(entry, path.rotation);

        TimelineAsset timeline = ScriptableObject.CreateInstance<TimelineAsset>();
        AssetDatabase.CreateAsset(timeline, BarPath);
        timeline.durationMode = TimelineAsset.DurationMode.FixedLength;
        timeline.fixedDuration = 12d;
        director.playableAsset = timeline;
        AnimationTrack track = timeline.CreateTrack<AnimationTrack>(null,
            "First Person - Look Around / Find Dealer / Approach");
        track.trackOffset = TrackOffset.ApplyTransformOffsets;
        track.position = Vector3.zero;
        track.rotation = Quaternion.identity;
        director.SetGenericBinding(track, pathAnimator);
        AnimationClip motion = new AnimationClip { name = "Bar Camera Position and Look Keys", frameRate = 60f };
        AssetDatabase.AddObjectToAsset(motion, timeline);
        float[] times = { 0f, 1.2f, 2.8f, 4.4f, 5.8f, 6.5f, 8.8f, 11.4f, 12f };
        Vector3[] positions = { entry, entry, entry, entry, entry, entry, middle, end, end };
        Vector3[] rotations = {
            new Vector3(0f, 90f, 0f), new Vector3(0f, 90f, 0f),
            new Vector3(-4f, 52f, 0f), new Vector3(3f, 137f, 0f),
            Look(entry, target), Look(entry, target), Look(middle, target), Look(end, target), Look(end, target)
        };
        for (int i = 1; i < rotations.Length; i++)
            rotations[i] = rotations[i - 1] + new Vector3(
                Mathf.DeltaAngle(rotations[i - 1].x, rotations[i].x),
                Mathf.DeltaAngle(rotations[i - 1].y, rotations[i].y), 0f);
        WriteCurves(motion, "m_LocalPosition", times, positions);
        WriteCurves(motion, "localEulerAnglesRaw", times, rotations);
        TimelineClip clip = track.CreateClip<AnimationPlayableAsset>();
        clip.displayName = "Handoff 0-1.2 | Look 1.2-4.4 | Discover 4.4-6.5 | Walk 6.5-11.4";
        clip.duration = 12d;
        var playable = (AnimationPlayableAsset)clip.asset;
        playable.clip = motion;
        playable.removeStartOffset = false;
        playable.applyFootIK = false;
        playable.loop = AnimationPlayableAsset.LoopMode.Off;

        string oldDoorPath = AssetDatabase.GetAssetPath(doorDirector.playableAsset);
        if (oldDoorPath != DoorPath)
            Require(string.IsNullOrEmpty(AssetDatabase.MoveAsset(oldDoorPath, DoorPath)), "Could not rename door Timeline.");
        doorDirector.name = "Door Open Sequence";
        doorDirector.playOnAwake = false;
        doorDirector.extrapolationMode = DirectorWrapMode.Hold;

        // Reuse the scene's TMP font/material by cloning its existing Next label.
        TMP_Text source = All<TMP_Text>(scene).First(t => t.name == "Next Text");
        GameObject prompt = UnityEngine.Object.Instantiate(source.gameObject, source.canvas.transform);
        prompt.name = "Dealer E Prompt";
        TMP_Text promptText = prompt.GetComponent<TMP_Text>();
        promptText.text = "E  Interact";
        promptText.fontSize = 30;
        promptText.alignment = TextAlignmentOptions.Center;
        promptText.raycastTarget = false;
        RectTransform rect = prompt.GetComponent<RectTransform>();
        rect.anchorMin = rect.anchorMax = new Vector2(0.5f, 0.18f);
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.anchoredPosition = Vector2.zero;
        rect.sizeDelta = new Vector2(400f, 65f);
        prompt.SetActive(false);

        Set(flow, "playerMove", player);
        Set(flow, "playerViewCamera", playerView);
        Set(flow, "outputCamera", main);
        Set(flow, "barDirector", director);
        Set(flow, "barCamera", rig);
        Set(flow, "dealerLookTarget", target);
        Set(flow, "interactionPrompt", prompt);
        Set(flow, "dialogueController", dialogue);
        Set(flow, "fadeController", fade);
        var fields = new SerializedObject(flow);
        var lines = fields.FindProperty("dialogueLines");
        string[] preserved = { "하이용 ", "게임 시작하기 전에", "이거 해보세요~ ", "좋아용",
            "이번엔 이거 해보세요~ ", "그럼 바로 게임하러 가실까요 " };
        lines.arraySize = preserved.Length;
        for (int i = 0; i < preserved.Length; i++) lines.GetArrayElementAtIndex(i).stringValue = preserved[i];
        fields.ApplyModifiedPropertiesWithoutUndo();
        Set(door, "introFlowController", flow);

        Require(Vector3.Distance(model.position, modelPosition) < 0.0001f &&
            Quaternion.Angle(model.rotation, modelRotation) < 0.001f, "New dealer placement changed.");
        EditorUtility.SetDirty(timeline);
        AssetDatabase.SaveAssets();
        EditorSceneManager.MarkSceneDirty(scene);
        IntroBarRevisionEditor.ApplyOpenScene();
        Debug.Log("Final Intro configured using the locally placed PF_Dealer; save the scene.");
    }

    [MenuItem("Tools/Intro/Validate Final Intro")]
    public static void ValidateOpenScene()
    {
        Scene scene = SceneManager.GetActiveScene();
        Require(scene.path == IntroPath, "Open Intro.");
        Require(All<Camera>(scene).Count(c => c.enabled && c.gameObject.activeInHierarchy) == 1, "Expected one rendering Camera.");
        Require(All<AudioListener>(scene).Count(c => c.enabled && c.gameObject.activeInHierarchy) == 1, "Expected one AudioListener.");
        Require(All<CinemachineBrain>(scene).Count(c => c.enabled) == 1, "Expected one enabled Brain.");
        Require(All<IntroFlowController>(scene).Count() == 1, "Expected one Intro flow.");
        foreach (var go in All<Transform>(scene).Select(t => t.gameObject))
            Require(GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(go) == 0, "Missing script: " + go.name);
        foreach (var director in All<PlayableDirector>(scene))
        {
            Require(!director.playOnAwake && director.playableAsset != null, "Director auto-play or missing asset.");
            foreach (var output in director.playableAsset.outputs)
                Require(director.GetGenericBinding(output.sourceObject) != null, "Missing binding: " + output.streamName);
        }
        Require(All<PlayableDirector>(scene).Count() == 2, "Expected DoorOpen and BarSequence only.");
        var flowFields = new SerializedObject(All<IntroFlowController>(scene).Single());
        foreach (string name in new[] { "playerMove", "playerViewCamera", "outputCamera", "barDirector",
            "barCamera", "dealerLookTarget", "interactionPrompt", "dialogueController", "fadeController",
            "holdToSkip", "doorDirector" })
            Require(flowFields.FindProperty(name).objectReferenceValue != null, "Missing flow reference: " + name);
        var holdFields = new SerializedObject(All<IntroHoldToSkip>(scene).Single());
        foreach (string name in new[] { "flow", "keycap", "outline" })
            Require(holdFields.FindProperty(name).objectReferenceValue != null, "Missing skip reference: " + name);
        Require(All<IntroKeycapOutline>(scene).Count() == 2, "Expected E and ESC keycaps.");
        foreach (var outline in All<IntroKeycapOutline>(scene))
            Require(outline.GetComponent<CanvasRenderer>() != null, "Keycap renderer missing.");
        Require(All<Transform>(scene).Any(t => t.name == "PF_Dealer"), "Local dealer missing.");
        Require(!All<Transform>(scene).Any(t => t.name == "Intro Dealer Humanoid"), "Old dealer remains.");
        Debug.Log("Final Intro validation passed: cameras, listeners, two Timelines and flow bindings.");
    }

    private static Vector3 Look(Vector3 from, Transform to) => Quaternion.LookRotation(to.position - from).eulerAngles;
    private static void WriteCurves(AnimationClip clip, string property, float[] times, Vector3[] values)
    {
        for (int axis = 0; axis < 3; axis++)
        {
            var curve = new AnimationCurve(times.Select((time, i) => new Keyframe(time, values[i][axis])).ToArray());
            for (int i = 0; i < curve.length; i++)
            {
                AnimationUtility.SetKeyLeftTangentMode(curve, i, AnimationUtility.TangentMode.ClampedAuto);
                AnimationUtility.SetKeyRightTangentMode(curve, i, AnimationUtility.TangentMode.ClampedAuto);
            }
            AnimationUtility.SetEditorCurve(clip, EditorCurveBinding.FloatCurve("", typeof(Transform),
                property + "." + "xyz"[axis]), curve);
        }
    }
    private static T[] All<T>(Scene scene) where T : Component =>
        scene.GetRootGameObjects().SelectMany(r => r.GetComponentsInChildren<T>(true)).ToArray();
    private static Transform Find(Scene scene, string name) => All<Transform>(scene).Single(t => t.name == name);
    private static void Set(UnityEngine.Object target, string property, UnityEngine.Object value)
    {
        var fields = new SerializedObject(target);
        fields.FindProperty(property).objectReferenceValue = value;
        fields.ApplyModifiedPropertiesWithoutUndo();
    }
    private static void Require(bool condition, string message)
    {
        if (!condition) throw new InvalidOperationException(message);
    }
}
